compile_src:
	javac -d bin src/*.java

compile_binary:
	javac -d bin src/binary/*.java

compile_files:
	javac -d bin src/files/*.java

compile_list:
	javac -d bin src/list/*.java

compile_all: compile_src compile_binary compile_files compile_list